---
title: "Data Cleaning"
author: "Vivian Zhang"
date: "8/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(janitor)
library(broom)
library(readxl)
library(tidyverse)

```

```{r FIPS}

merge_fips <- read_csv("unemployment_data/AllUnemploymentRatesFromJan20.csv") %>%
  clean_names() %>%
  select(2,3,6)

```


```{r employment}

education <- read_excel("viv_data/original_docs/Education.xls", skip = 4) %>%
  clean_names()

education <- education %>%
  filter(area_name != "United States") %>%
  select(c(2,3,44,45,46,47)) %>%
  rename(county = area_name) %>%
  separate(county, c("county", "junk"), " C") %>%
  na.omit() %>%
  select(-junk) %>%
  full_join(merge_fips, by ="county")

write.csv(education,"education_attainment.csv")

```

```{r median household income}

median_income <- read_csv("viv_data/original_docs/median_income.csv", skip = 1) %>%
  clean_names()

median_income <- median_income %>%
  separate(geographic_area_name, c("county", "State"), ",") %>%
  select(c(2,3,41,42,43,44)) %>%
  separate(county, c("county", "Junk"), " C") %>%
  na.omit() %>%
  select(-Junk) %>%
  full_join(merge_fips, by ="county")

write.csv(median_income,"income.csv")

```

```{r racial and ethnic data}

race_data <- read_csv("viv_data/original_docs/race_3.csv", skip = 1) %>%
  clean_names()

race_data <- race_data %>%
  separate(geographic_area_name, c("county", "State"), ",") %>%
  select(2,3,estimate_race_total_population, starts_with("percent_estimate"), -1) %>%
  select(-c(4:8)) %>%
  separate(county, c("county", "Junk"), " C") %>%
  na.omit() %>%
  select(-Junk)

race_data <- race_data %>%
  select(1,2,31,32,33,34,35,38) %>%
  rename(percent_white = percent_estimate_race_alone_or_in_combination_with_one_or_more_other_races_total_population_white,
         percent_black = percent_estimate_race_alone_or_in_combination_with_one_or_more_other_races_total_population_black_or_african_american,
         percent_indigenous = percent_estimate_race_alone_or_in_combination_with_one_or_more_other_races_total_population_american_indian_and_alaska_native,
         percent_asian = percent_estimate_race_alone_or_in_combination_with_one_or_more_other_races_total_population_asian,
         percent_pacific_islander = percent_estimate_race_alone_or_in_combination_with_one_or_more_other_races_total_population_native_hawaiian_and_other_pacific_islander,
         percent_hispanic_latino = percent_estimate_hispanic_or_latino_and_race_total_population_hispanic_or_latino_of_any_race) %>%
  full_join(merge_fips, by ="county")

write.csv(race_data,"racedata.csv")

```

```{r internet access}

internet <- read_excel("viv_data/original_docs/broad_band.xlsx") %>%
  clean_names()

internet <- internet %>%
  select(-1) %>%
  group_by(state) %>%
  arrange(state, county) %>%
  full_join(merge_fips, by ="county")

write.csv(internet,"internet.csv")

```


